# Generated by Django 5.1.1 on 2024-09-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_cliente_correo_cliente_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fecha_venta',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(default=321, max_length=15),
            preserve_default=False,
        ),
    ]
