# Generated by Django 5.1.1 on 2024-09-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_proveedor_direccion_remove_venta_fecha_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(default=320, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
